### PR TITLE
finished quiz.js

### PR DESCRIPTION
**Pull request by scottpschaffer**
Not sure if all of my comments obscure the code I wrote.

### CODE REVIEW

**Comment by gregkorte** [comment]
Scott! Nice job on your quiz. The functionality you have submitted all works properly, and the error checking is thorough. The only thing missing is the `Enter` button functionality. When a user presses `Enter` from either input field your code should run. Resubmit when you think you've got it, and I'll look over it.

**Comment by scottpschaffer** [comment]
Greg,

My apologies for missing the part regarding pressing the Enter key. I saw the word "either" in the sentence and thought that I could implement it one way OR the other way, not both ways. I'll work on it tonight and try to have something by tomorrow.

Scott

**Comment by scottpschaffer** [comment]
Added the Enter Key functionality to the Text Boxes and added a "Console Clear" whenever it runs.

**Comment by gregkorte** [comment]
Nice job, Scott! :+1:

**Pull request merged**
